name: form_builder_file_picker
description: FilePicker Field for flutter_form_builder package. Used to select files as part of form input.
version: 6.0.0
homepage: https://github.com/sportner/form_builder_file_picker

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_form_builder:
    git: https://github.com/Sportner/flutter_form_builder.git
  file_picker: 3.0.1
  permission_handler: ^6.1.1
  community_material_icon: ^5.9.55

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
